name: cchess_engine
description: Jdt Pikafish base on pikafish_engine 1.0.3
version: 1.0.1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pikafish_engine: ^1.0.3
  date_format: ^2.0.7
  path_provider: ^2.1.1

  ffi: ^2.0.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pikafish.nnue